name: sms
services:
  client:
    image: "node:24-alpine"
    volumes:
      - ./client:/app
    ports:
      - 3000:3000
    working_dir: /app
    command: ["/bin/sh", "-c", "npm i && npm run dev"]
    environment:
      - WATCHPACK_POLLING=true
      - VITE_HOST=localhost:8000
      - VITE_PROD=false
  
  server:
    image: python:3.12-alpine
    volumes:
      - ./server:/app
    working_dir: /app
    ports:
      - 8000:8000
    env_file:
      - ./server/.env.dev.sample
    command: ["/bin/sh", "-c", "pip install -r requirements.txt && fastapi dev main.py --host 0.0.0.0"]
  
  cache:
    image: "redis:alpine"

  db:
    image: "postgres:18-alpine"
    environment:
      - POSTGRES_DB=sms
      - POSTGRES_USER=sms
      - POSTGRES_PASSWORD=password