name: marketflow
services:
  client:
    image: "node:24-alpine"
    volumes:
      - ./client:/app
    ports:
      - 3000:3000
    working_dir: /app
    command: ["/bin/sh", "-c", "npm i && npm run dev"]
    environment:
      - WATCHPACK_POLLING=true
      - VITE_HOST=localhost:8000
      - VITE_PROD=false
      
  api:
    image: python:3.12-alpine
    volumes:
      - ./server/api:/app
    working_dir: /app
    ports:
      - 8000:8000
    environment:
      - ADMIN_USERNAME=ecell_admin
      - ADMIN_PASSWORD=ecell_admin
      - SECRET=insecure_key
      - DB_URL=postgres://marketflow:password@db/marketflow
      - CACHE_HOST=cache
      - CACHE_PORT=6379
      - ENGINE_HOST=http://engine:8000
      - TORTOISE_ORM=lib.db.TORTOISE_ORM
    command: ["/bin/sh", "-c", "pip install -r requirements.txt && fastapi dev main.py --host 0.0.0.0"]
  
  engine:
    image: python:3.12-alpine
    volumes:
      - ./server/engine:/app
    working_dir: /app
    environment:
      - DB_URL=postgres://marketflow:password@db/marketflow
      - CACHE_HOST=cache
      - CACHE_PORT=6379
    command: ["/bin/sh", "-c", "pip install -r requirements.txt && fastapi dev main.py --host 0.0.0.0"]

  cache:
    image: "redis:alpine"

  db:
    image: "postgres:18-alpine"
    environment:
      - POSTGRES_DB=marketflow
      - POSTGRES_USER=marketflow
      - POSTGRES_PASSWORD=password